main:
  web_trigger_update: &web_trigger_update
    - name: Update Docker images
      services:
        - docker
      stages:
        - name: download models
          script: |
            set -e
            mkdir -p models-enzh/enzh models-enja/enja
            models_json_url="https://storage.googleapis.com/moz-fx-translations-data--303e-prod-translations-data/db/models.json"
            echo "Fetching models.json from $models_json_url"
            curl -fsSL "$models_json_url" -o models.json
            base_url=$(jq -r '.baseUrl' models.json)

            echo "Downloading en-zh model..."
            model_data_enzh=$(jq -r '.models."en-zh"[0]' models.json)
            for key in lex model srcVocab trgVocab; do
              file_path=$(echo "$model_data_enzh" | jq -r ".files.${key}.path")
              file=$(basename "$file_path")
              echo "  Downloading $file"
              curl -fsSL "$base_url/$file_path" -o "models-enzh/enzh/$file"
              gunzip -f "models-enzh/enzh/$file" 2>/dev/null || true
            done

            echo "Downloading en-ja model..."
            model_data_enja=$(jq -r '.models."en-ja"[0]' models.json)
            for key in lex model srcVocab trgVocab; do
              file_path=$(echo "$model_data_enja" | jq -r ".files.${key}.path")
              file=$(basename "$file_path")
              echo "  Downloading $file"
              curl -fsSL "$base_url/$file_path" -o "models-enja/enja/$file"
              gunzip -f "models-enja/enja/$file" 2>/dev/null || true
            done

            rm -f models.json
            echo "Download completed"
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: docker build
          script: |
            # Copy models
            cp -r models-enzh/enzh models/
            cp -r models-enja/enja models/
            docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest